### PR TITLE
Add logo variation 'Facet'

### PR DESCRIPTION
**Pull request by maryshak1996**
Adding black and white text options for the Facet addition to the logo

### CODE REVIEW

**Comment by knowncitizen** [comment]
I thought about creating docs/images but then docs would have been empty. For now I think it's fine to just move the logo into src/images to replace logo.png

**Comment by knowncitizen** [comment]
When we merge, let's do the optional squash if that's OK with you @maryshak1996

**Comment by knowncitizen** [comment]
Very minor change - metalkube_facet-black-text.png vs. metalkube_facet-blacktext.svg - why the extra hyphen? This is a nit pick, but I am curious.

**Comment by maryshak1996** [comment]
@knowncitizen huhhh that's funky... must have just been a typo on my end. I can update if you want

**Comment by knowncitizen** [comment]
Would be great.

**Pull request merged**
